var db = require('../configuration/database/db_sql')
const Sequelize = require('sequelize');
const trlawsuit = db.define('trlawsuit', {
  lawsuitId: { primaryKey: true, autoIncrement: true, type: Sequelize.INTEGER, allowNull: false },
  documentNumber: { type: Sequelize.STRING(50), allowNull: true },
  debtCollectionNumber: { type: Sequelize.STRING(25), allowNull: true },
  idcard: { type: Sequelize.STRING(25), allowNull: true },
  propertyId: { type: Sequelize.INTEGER, allowNull: true },
  lawsuitType: { type: Sequelize.STRING(25), allowNull: true },
  lawyerName: { type: Sequelize.STRING(255), allowNull: true },
  capitalSuedPay: { type: Sequelize.INTEGER, allowNull: true },
  dateOfIntroduction: { type: Sequelize.DATE, allowNull: true },
  responsible: { type: Sequelize.STRING(255), allowNull: true },
  filingDate: { type: Sequelize.DATE, allowNull: true },
  InvestigationDate: { type: Sequelize.STRING, allowNull: true },
  court: { type: Sequelize.STRING(255), allowNull: true },
  courtDate: { type: Sequelize.DATE, allowNull: true },
  sequel: { type: Sequelize.STRING(255), allowNull: true },
  otherDetails: { type: Sequelize.STRING, allowNull: true },
  sentence: { type: Sequelize.STRING, allowNull: true },
  amountVerdict: { type: Sequelize.INTEGER, allowNull: true },
  lawyerFee: { type: Sequelize.INTEGER, allowNull: true },
  fee: { type: Sequelize.INTEGER, allowNull: true },
  litigationCosts: { type: Sequelize.INTEGER, allowNull: true },
  courtFees: { type: Sequelize.INTEGER, allowNull: true },
  amountOther: { type: Sequelize.INTEGER, allowNull: true },
  amountOtherNote: { type: Sequelize.STRING, allowNull: true },
  paymentAmount: { type: Sequelize.INTEGER, allowNull: true },
  status: { type: Sequelize.STRING(10), allowNull: true },
  active: { type: Sequelize.STRING(1), allowNull: true },
  remark: { type: Sequelize.STRING, allowNull: true },
  createdBy: { type: Sequelize.STRING(50), allowNull: true },
  createDate: { type: Sequelize.DATE, allowNull: true },
  updatedBy: { type: Sequelize.STRING(50), allowNull: true },
  updateDate: { type: Sequelize.DATE, allowNull: true },
  sourceId: { type: Sequelize.STRING(50), allowNull: true },
  source: { type: Sequelize.STRING(50), allowNull: true },
}, { tableName: 'trlawsuit' });
module.exports = trlawsuit;